spring:
  application:
    name: RestAPI
  datasource:
    url: jdbc:postgresql://193.57.136.79:5432/avito?stringtype=unspecified
    username: belunin
    password: passwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hbm2ddl:
        auto: none
      show_sql: true
  flyway:
    clean-disabled: false

server:
  port: 8080

logging:
  level:
    org.springframework.web: TRACE
    org.apache.catalina: TRACE
